ALTER TABLE dbo.customer
ALTER COLUMN purchase_amount float;

--Q1: What is the total revenue generated by male vs female customers?
--select
--	gender,
--	sum(purchase_amount) as Revenue
--from customer
--group by gender;

--Q2: Which customers used a discount but still spent more than the average purchase amount?
select
	customer_id,
	Avg(purchase_amount) as Avg_purchase
from customer
where discount_applied = 'yes' and purchase_amount >=(select Avg(purchase_amount) from customer) 
group by customer_id;

-- Q3: Which are the top 5 products with the highest review rating?
select Top 5
	item_purchased,
	round(avg(review_rating),2) as Avg_review
from customer
group by item_purchased
order by avg(review_rating) Desc

-- Q4: Compare the Avg Purchase Amounts between Standard and Express Shipping
select
	shipping_type,
	Avg(purchase_amount) as Avg_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5: Subcribed customers spend more? Compare average and total revenue between subscribes and non-subscribe
select
	subscription_status,
	round(AVG(purchase_amount),2) as avg_purchase,
	round(sum(purchase_amount),2) as total_revenue,
	count(customer_id) as count_customer
from customer
group by subscription_status
order by total_revenue;

--Q6: Which 5 products have the highest percentage of purchase with discounts applied?
select Top 5
	item_purchased,
	(100*sum(case when discount_applied='Yes' then 1 Else 0 end)/count(*))  as discount_rate
from customer
group by item_purchased
order by discount_rate DESC;

--Q7 Segment customers into New, Returning and Loyal based on their total
--number of previous purchase, and show the count of each sgment
with customer_type as(
	select
		customer_id,
		case 
			when previous_purchases =1 then 'New'
			when previous_purchases between 2 and 10 then 'Returning'
			when previous_purchases >10 then 'Loyal'
			End as Segment_group
	from customer
)
select 
	Segment_group,
	count(*) as Number_Customer
from customer_type
group by Segment_group;

--Q8: What are the top 3 most purchased products within each category?
with item_counts as (
	select
		category,
		item_purchased,
		count(customer_id) as total_orders,
		row_number () over(partition by category order by count(customer_id)Desc) as RN
	from customer
	group by category,item_purchased
)
select
	category,
	item_purchased,
	total_orders
from item_counts
where RN <=3

--Q9: Are customer who are repeat buyers(more than 5 previous purchase) also likely to subcribes?
select
	subscription_status,
	count(customer_id) as repeat_customer
from customer
where previous_purchases >5
group by subscription_status;

--Q10: What is the revenue contribute of each age group
select 
	age_group,
	sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC
